name: pdf_render_plus
description: Fork of espresso3389/flutter_pdf_render with 16 KB page-size support and maintenance.
version: 2.0.0
homepage: https://github.com/ynnob/pdf_render_plus
repository: https://github.com/ynnob/pdf_render_plus
issue_tracker: https://github.com/ynnob/pdf_render_plus/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  plugin_platform_interface: ^2.1.8
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: jp.espresso3389.pdf_render
        pluginClass: PdfRenderPlugin
      ios:
        pluginClass: PdfRenderPlugin
      macos:
        pluginClass: SwiftPdfRenderPlugin
      web:
        pluginClass: PdfRenderWebPlugin
        fileName: src/web/pdf_render_web_plugin.dart
